// <auto-generated />
using System;
using Listomora.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Listomora.DAL.Migrations
{
    [DbContext(typeof(ListomoraDbContext))]
    partial class ListomoraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Listomora.Domain.Model.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArticleType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Article");

                    b.HasIndex("CreatorId");

                    b.ToTable("Articles");

                    b.HasDiscriminator<string>("ArticleType").HasValue("Article");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("bdf2a31b-5e8f-4874-838d-3246a804ae13"),
                            IsPublic = true,
                            Name = "Raquette de padel"
                        },
                        new
                        {
                            Id = new Guid("6a03f6d7-9160-4d0f-b94b-dbc41d497ec8"),
                            IsPublic = true,
                            Name = "Papier toilette double épaisseur"
                        },
                        new
                        {
                            Id = new Guid("34a8bda4-f77f-42e5-ba61-2b511985c4db"),
                            IsPublic = true,
                            Name = "Crayons"
                        },
                        new
                        {
                            Id = new Guid("bb861dfa-889d-49c3-ad76-407d662dd7c2"),
                            IsPublic = true,
                            Name = "Produit vaiselle"
                        },
                        new
                        {
                            Id = new Guid("06effa04-6bcf-401f-a091-00b24f6ba8f0"),
                            IsPublic = true,
                            Name = "Sacs poubelle 30 litres"
                        },
                        new
                        {
                            Id = new Guid("f15deb6c-e587-421c-b0cf-1ea1640df7b3"),
                            IsPublic = true,
                            Name = "Déodorant AXE YOU 48H"
                        });
                });

            modelBuilder.Entity("Listomora.Domain.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DisableDate")
                        .HasColumnType("DateTime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("User");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            Email = "john@cena.us",
                            FirstName = "John",
                            LastName = "Cena",
                            Password = "AQAAAAIAAYagAAAAENPe+GBHwVUPi9G/MzOxT6Dbsx2WCXHCl+Vc7l//HljQLfj3IPQyNBM0pQAf03H9KA==",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Listomora.Domain.Model.Ingredient", b =>
                {
                    b.HasBaseType("Listomora.Domain.Model.Article");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cae52516-7547-4d4e-a289-358fd8891a98"),
                            IsPublic = true,
                            Name = "Pommes de terre",
                            Category = "CEREALS"
                        },
                        new
                        {
                            Id = new Guid("e5bebf1e-bd35-448c-a1a2-941e55687ff5"),
                            IsPublic = true,
                            Name = "Viande de veau",
                            Category = "MEAT"
                        },
                        new
                        {
                            Id = new Guid("1ed84abe-4c15-458f-82b8-a5a9bc34b5b5"),
                            IsPublic = true,
                            Name = "Filet de saumon",
                            Category = "FISH_AND_SEAFOODS"
                        },
                        new
                        {
                            Id = new Guid("82a56879-1d59-40f6-8a20-75cdcd2fe686"),
                            IsPublic = true,
                            Name = "Emmental rapé",
                            Category = "DAIRY_PRODUCTS"
                        },
                        new
                        {
                            Id = new Guid("97505262-64f9-4444-83cf-67c93d8161d5"),
                            IsPublic = true,
                            Name = "Blanc de poulet",
                            Category = "MEAT"
                        },
                        new
                        {
                            Id = new Guid("97796814-4f88-40a6-8d3d-98f46135be41"),
                            IsPublic = true,
                            Name = "Sel",
                            Category = "CONDIMENTS"
                        },
                        new
                        {
                            Id = new Guid("16c4a654-0f04-40eb-a23e-9d580c7062a8"),
                            IsPublic = true,
                            Name = "Poivre",
                            Category = "CONDIMENTS"
                        },
                        new
                        {
                            Id = new Guid("3d11a56b-1b6a-4581-940a-36eb4c25d01c"),
                            IsPublic = true,
                            Name = "Spaghetti",
                            Category = "CEREALS"
                        });
                });

            modelBuilder.Entity("Listomora.Domain.Model.Article", b =>
                {
                    b.HasOne("Listomora.Domain.Model.User", "User")
                        .WithMany("CreatedArticles")
                        .HasForeignKey("CreatorId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Listomora.Domain.Model.User", b =>
                {
                    b.Navigation("CreatedArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
