// <auto-generated />
using System;
using Listomora.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Listomora.Infrastructure.Migrations
{
    [DbContext(typeof(ListomoraDbContext))]
    partial class ListomoraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Listomora.Domain.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArticleType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Article");

                    b.HasIndex("CreatorId");

                    b.ToTable("Articles");

                    b.HasDiscriminator<string>("ArticleType").HasValue("Article");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("bdf2a31b-5e8f-4874-838d-3246a804ae13"),
                            CreatorId = new Guid("6ad52029-0225-48c4-a2b5-7aa35fec7056"),
                            IsPublic = false,
                            Name = "Raquette de padel"
                        },
                        new
                        {
                            Id = new Guid("6a03f6d7-9160-4d0f-b94b-dbc41d497ec8"),
                            CreatorId = new Guid("6ad52029-0225-48c4-a2b5-7aa35fec7056"),
                            IsPublic = false,
                            Name = "Papier toilette double épaisseur"
                        },
                        new
                        {
                            Id = new Guid("34a8bda4-f77f-42e5-ba61-2b511985c4db"),
                            CreatorId = new Guid("0eb2993d-7fd5-4f29-9172-1b8f6aa80736"),
                            IsPublic = true,
                            Name = "Crayons"
                        },
                        new
                        {
                            Id = new Guid("bb861dfa-889d-49c3-ad76-407d662dd7c2"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = false,
                            Name = "Produit vaiselle"
                        },
                        new
                        {
                            Id = new Guid("06effa04-6bcf-401f-a091-00b24f6ba8f0"),
                            CreatorId = new Guid("6ad52029-0225-48c4-a2b5-7aa35fec7056"),
                            IsPublic = true,
                            Name = "Sacs poubelle 30 litres"
                        },
                        new
                        {
                            Id = new Guid("f15deb6c-e587-421c-b0cf-1ea1640df7b3"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Déodorant AXE YOU 48H"
                        });
                });

            modelBuilder.Entity("Listomora.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DisableDate")
                        .HasColumnType("DateTime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_User_Role", "[Role] IN (0,1)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@cena.us",
                            FirstName = "John",
                            LastName = "Cena",
                            Password = "$argon2id$v=19$m=65536,t=3,p=1$ev4diG4da7RDMn1FvRnwNg$l0gZikrMkHCCnl3wfm5pw/udnWV3+qv1jJ3lbJ9OK5c",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("6ad52029-0225-48c4-a2b5-7aa35fec7056"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cr7@goat.com",
                            FirstName = "Cristiano",
                            LastName = "Ronaldo",
                            Password = "$argon2id$v=19$m=65536,t=3,p=1$szQt55zx0faZ4uPwde+z6w$zRT3vvQW42okClFQ4AcqvtNRgq8J5lO04VS6wuNTDWY",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("0eb2993d-7fd5-4f29-9172-1b8f6aa80736"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lm10@goat.com",
                            FirstName = "Lionel",
                            LastName = "Messi",
                            Password = "$argon2id$v=19$m=65536,t=3,p=1$bG4MFO5fRMx7DG/Mxx8g8A$6zCu9QvFF927JPtL+BWIZwnE51vD9nOYDSWkwdAxZWw",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Listomora.Domain.Models.Ingredient", b =>
                {
                    b.HasBaseType("Listomora.Domain.Models.Article");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cae52516-7547-4d4e-a289-358fd8891a98"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Pommes de terre",
                            Category = "CEREALS"
                        },
                        new
                        {
                            Id = new Guid("e5bebf1e-bd35-448c-a1a2-941e55687ff5"),
                            CreatorId = new Guid("6ad52029-0225-48c4-a2b5-7aa35fec7056"),
                            IsPublic = false,
                            Name = "Viande de veau",
                            Category = "MEAT"
                        },
                        new
                        {
                            Id = new Guid("1ed84abe-4c15-458f-82b8-a5a9bc34b5b5"),
                            CreatorId = new Guid("0eb2993d-7fd5-4f29-9172-1b8f6aa80736"),
                            IsPublic = true,
                            Name = "Filet de saumon",
                            Category = "FISH_AND_SEAFOODS"
                        },
                        new
                        {
                            Id = new Guid("82a56879-1d59-40f6-8a20-75cdcd2fe686"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Emmental rapé",
                            Category = "DAIRY_PRODUCTS"
                        },
                        new
                        {
                            Id = new Guid("97505262-64f9-4444-83cf-67c93d8161d5"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = false,
                            Name = "Blanc de poulet",
                            Category = "MEAT"
                        },
                        new
                        {
                            Id = new Guid("97796814-4f88-40a6-8d3d-98f46135be41"),
                            CreatorId = new Guid("6ad52029-0225-48c4-a2b5-7aa35fec7056"),
                            IsPublic = true,
                            Name = "Sel",
                            Category = "CONDIMENTS"
                        },
                        new
                        {
                            Id = new Guid("16c4a654-0f04-40eb-a23e-9d580c7062a8"),
                            CreatorId = new Guid("0eb2993d-7fd5-4f29-9172-1b8f6aa80736"),
                            IsPublic = false,
                            Name = "Poivre",
                            Category = "CONDIMENTS"
                        },
                        new
                        {
                            Id = new Guid("3d11a56b-1b6a-4581-940a-36eb4c25d01c"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Spaghetti",
                            Category = "CEREALS"
                        });
                });

            modelBuilder.Entity("Listomora.Domain.Models.Article", b =>
                {
                    b.HasOne("Listomora.Domain.Models.User", "Creator")
                        .WithMany("CreatedArticles")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_Article_Creator");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Listomora.Domain.Models.User", b =>
                {
                    b.Navigation("CreatedArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
