// <auto-generated />
using System;
using Listomora.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Listomora.Infrastructure.Migrations
{
    [DbContext(typeof(ListomoraDbContext))]
    partial class ListomoraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Listomora.Domain.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArticleType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Article");

                    b.HasIndex("CreatorId");

                    b.ToTable("Article", (string)null);

                    b.HasDiscriminator<string>("ArticleType").HasValue("Article");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("bdf2a31b-5e8f-4874-838d-3246a804ae13"),
                            CreatorId = new Guid("6ad52029-0225-48c4-a2b5-7aa35fec7056"),
                            IsPublic = false,
                            Name = "Raquette de padel"
                        },
                        new
                        {
                            Id = new Guid("6a03f6d7-9160-4d0f-b94b-dbc41d497ec8"),
                            CreatorId = new Guid("6ad52029-0225-48c4-a2b5-7aa35fec7056"),
                            IsPublic = false,
                            Name = "Papier toilette double épaisseur"
                        },
                        new
                        {
                            Id = new Guid("34a8bda4-f77f-42e5-ba61-2b511985c4db"),
                            CreatorId = new Guid("0eb2993d-7fd5-4f29-9172-1b8f6aa80736"),
                            IsPublic = true,
                            Name = "Crayons"
                        },
                        new
                        {
                            Id = new Guid("bb861dfa-889d-49c3-ad76-407d662dd7c2"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = false,
                            Name = "Produit vaiselle"
                        },
                        new
                        {
                            Id = new Guid("06effa04-6bcf-401f-a091-00b24f6ba8f0"),
                            CreatorId = new Guid("6ad52029-0225-48c4-a2b5-7aa35fec7056"),
                            IsPublic = true,
                            Name = "Sacs poubelle 30 litres"
                        },
                        new
                        {
                            Id = new Guid("f15deb6c-e587-421c-b0cf-1ea1640df7b3"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Déodorant AXE YOU 48H"
                        },
                        new
                        {
                            Id = new Guid("d6acb86d-856e-4874-9d64-73a1f3e2f8e9"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Savon liquide Palmolive"
                        },
                        new
                        {
                            Id = new Guid("6ef48e96-a40a-4dc5-9432-fe6d85c87bb6"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Mouchoirs"
                        },
                        new
                        {
                            Id = new Guid("c7e03ae1-353c-4e21-963f-ff906d09506c"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Coca-Cola"
                        },
                        new
                        {
                            Id = new Guid("be258d12-1679-4aa2-8b71-368b2c16b913"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Fanta"
                        },
                        new
                        {
                            Id = new Guid("d392cdc1-9141-4dc3-ac7e-a4486e2e8774"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Pizza surgelée"
                        },
                        new
                        {
                            Id = new Guid("336ac8ab-c997-4521-a3c1-9aaa5cb86fbb"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Chips Kroky paprika"
                        },
                        new
                        {
                            Id = new Guid("a456432d-33d1-44d9-be6a-8599bd02becc"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Dentifrice Colgate"
                        },
                        new
                        {
                            Id = new Guid("81bd4a7b-b60c-4e11-8d74-6c641721a928"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Piles AAA"
                        });
                });

            modelBuilder.Entity("Listomora.Domain.Models.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("DateTime2");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_ShoppingList");

                    b.HasIndex("CreatorId");

                    b.ToTable("ShoppingList", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("86a0fcf5-f62e-4809-a28b-a9403514991e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsDone = false,
                            IsTemplate = false,
                            Name = "Liste de courses du samedi 28 mars"
                        },
                        new
                        {
                            Id = new Guid("f132fcbf-bcd5-4ce9-ba7b-0dc102fabb72"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsDone = false,
                            IsTemplate = false,
                            Name = "Liste de courses de mercredi soir prochain"
                        },
                        new
                        {
                            Id = new Guid("5e47b154-be10-43bb-ad15-a09f83d77ff0"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            DoneAt = new DateTime(2026, 3, 7, 10, 32, 48, 0, DateTimeKind.Unspecified),
                            IsDone = true,
                            IsTemplate = false,
                            Name = "Liste de courses du samedi 7 mars"
                        },
                        new
                        {
                            Id = new Guid("49c7a8c0-0647-4380-a588-e8d88c039f06"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsDone = false,
                            IsTemplate = true,
                            Name = "Liste de courses habituelle"
                        });
                });

            modelBuilder.Entity("Listomora.Domain.Models.ShoppingListLine", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleId", "ShoppingListId")
                        .HasName("PK_ShoppingListLine");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListLine", (string)null);

                    b.HasData(
                        new
                        {
                            ArticleId = new Guid("c7e03ae1-353c-4e21-963f-ff906d09506c"),
                            ShoppingListId = new Guid("86a0fcf5-f62e-4809-a28b-a9403514991e"),
                            Amount = 6.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "LITER"
                        },
                        new
                        {
                            ArticleId = new Guid("6ef48e96-a40a-4dc5-9432-fe6d85c87bb6"),
                            ShoppingListId = new Guid("86a0fcf5-f62e-4809-a28b-a9403514991e"),
                            Amount = 2.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "PACK"
                        },
                        new
                        {
                            ArticleId = new Guid("336ac8ab-c997-4521-a3c1-9aaa5cb86fbb"),
                            ShoppingListId = new Guid("86a0fcf5-f62e-4809-a28b-a9403514991e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ArticleId = new Guid("d392cdc1-9141-4dc3-ac7e-a4486e2e8774"),
                            ShoppingListId = new Guid("86a0fcf5-f62e-4809-a28b-a9403514991e"),
                            Amount = 2.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "BOX"
                        },
                        new
                        {
                            ArticleId = new Guid("b09ea0c6-b53a-4a70-bff7-56dcfc5bb2d0"),
                            ShoppingListId = new Guid("86a0fcf5-f62e-4809-a28b-a9403514991e"),
                            Amount = 6.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "UNIT"
                        },
                        new
                        {
                            ArticleId = new Guid("4a5bda61-ac90-4faf-9ae1-139f81a17eb6"),
                            ShoppingListId = new Guid("86a0fcf5-f62e-4809-a28b-a9403514991e"),
                            Amount = 500.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "GRAM"
                        },
                        new
                        {
                            ArticleId = new Guid("edf88fdd-0117-4aa4-b3a5-17be26c913f9"),
                            ShoppingListId = new Guid("86a0fcf5-f62e-4809-a28b-a9403514991e"),
                            Amount = 2.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "LITER"
                        },
                        new
                        {
                            ArticleId = new Guid("ff0cdcf7-aee0-4b9e-b520-8d0fb3b93047"),
                            ShoppingListId = new Guid("f132fcbf-bcd5-4ce9-ba7b-0dc102fabb72"),
                            Amount = 500.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "GRAM"
                        },
                        new
                        {
                            ArticleId = new Guid("9e736920-7440-4376-b485-1f192e0d7470"),
                            ShoppingListId = new Guid("f132fcbf-bcd5-4ce9-ba7b-0dc102fabb72"),
                            Amount = 600.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "GRAM"
                        },
                        new
                        {
                            ArticleId = new Guid("e6f1fd6a-abb7-4d84-bca8-aeff139dc88c"),
                            ShoppingListId = new Guid("f132fcbf-bcd5-4ce9-ba7b-0dc102fabb72"),
                            Amount = 4.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "UNIT"
                        },
                        new
                        {
                            ArticleId = new Guid("46703052-e35c-4582-85a8-418f284e0ec8"),
                            ShoppingListId = new Guid("f132fcbf-bcd5-4ce9-ba7b-0dc102fabb72"),
                            Amount = 2.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "PACK"
                        },
                        new
                        {
                            ArticleId = new Guid("fcf05aed-90e9-47a0-b9b9-09af9bf0f2b9"),
                            ShoppingListId = new Guid("f132fcbf-bcd5-4ce9-ba7b-0dc102fabb72"),
                            Amount = 50.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "CENTILITER"
                        },
                        new
                        {
                            ArticleId = new Guid("924c8c5b-9684-4b77-b5d0-80b0f1cf8b30"),
                            ShoppingListId = new Guid("f132fcbf-bcd5-4ce9-ba7b-0dc102fabb72"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ArticleId = new Guid("d35633e3-34cb-48d2-aedc-5a65271357d2"),
                            ShoppingListId = new Guid("f132fcbf-bcd5-4ce9-ba7b-0dc102fabb72"),
                            Amount = 1.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "UNIT"
                        },
                        new
                        {
                            ArticleId = new Guid("3d956419-cd5b-41c5-9b2a-d7e5a990c838"),
                            ShoppingListId = new Guid("f132fcbf-bcd5-4ce9-ba7b-0dc102fabb72"),
                            Amount = 12.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "UNIT"
                        },
                        new
                        {
                            ArticleId = new Guid("c762d216-d6ab-43b6-bfe7-cab995c5aea9"),
                            ShoppingListId = new Guid("5e47b154-be10-43bb-ad15-a09f83d77ff0"),
                            Amount = 4.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "UNIT"
                        },
                        new
                        {
                            ArticleId = new Guid("ac07af80-640a-4270-9d48-62f8c9b84df6"),
                            ShoppingListId = new Guid("5e47b154-be10-43bb-ad15-a09f83d77ff0"),
                            Amount = 500.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "GRAM"
                        },
                        new
                        {
                            ArticleId = new Guid("794f67c2-7afb-495e-8570-6daad6cb4a0a"),
                            ShoppingListId = new Guid("5e47b154-be10-43bb-ad15-a09f83d77ff0"),
                            Amount = 6.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "UNIT"
                        },
                        new
                        {
                            ArticleId = new Guid("4c500d54-1468-4a8c-81f5-ff846fb36b3d"),
                            ShoppingListId = new Guid("5e47b154-be10-43bb-ad15-a09f83d77ff0"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ArticleId = new Guid("121a810d-3904-4cf1-9af4-063a2e56b62b"),
                            ShoppingListId = new Guid("5e47b154-be10-43bb-ad15-a09f83d77ff0"),
                            Amount = 2.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "CAN"
                        },
                        new
                        {
                            ArticleId = new Guid("48f07af2-eefb-4097-a479-cc50a3117851"),
                            ShoppingListId = new Guid("5e47b154-be10-43bb-ad15-a09f83d77ff0"),
                            Amount = 250.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "GRAM"
                        },
                        new
                        {
                            ArticleId = new Guid("21d579a9-b2ae-4434-b7d5-45201001bca1"),
                            ShoppingListId = new Guid("5e47b154-be10-43bb-ad15-a09f83d77ff0"),
                            Amount = 500.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "GRAM"
                        },
                        new
                        {
                            ArticleId = new Guid("d6acb86d-856e-4874-9d64-73a1f3e2f8e9"),
                            ShoppingListId = new Guid("49c7a8c0-0647-4380-a588-e8d88c039f06"),
                            Amount = 1.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "PACK"
                        },
                        new
                        {
                            ArticleId = new Guid("a456432d-33d1-44d9-be6a-8599bd02becc"),
                            ShoppingListId = new Guid("49c7a8c0-0647-4380-a588-e8d88c039f06"),
                            Amount = 1.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "BOX"
                        },
                        new
                        {
                            ArticleId = new Guid("81bd4a7b-b60c-4e11-8d74-6c641721a928"),
                            ShoppingListId = new Guid("49c7a8c0-0647-4380-a588-e8d88c039f06"),
                            Amount = 4.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "UNIT"
                        },
                        new
                        {
                            ArticleId = new Guid("1dd4a5f7-f93f-42ed-919d-c677f0dc0e7f"),
                            ShoppingListId = new Guid("49c7a8c0-0647-4380-a588-e8d88c039f06"),
                            Amount = 200.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "GRAM"
                        },
                        new
                        {
                            ArticleId = new Guid("aac50be3-c2ea-4642-a3d9-81f58299e012"),
                            ShoppingListId = new Guid("49c7a8c0-0647-4380-a588-e8d88c039f06"),
                            Amount = 4.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "UNIT"
                        },
                        new
                        {
                            ArticleId = new Guid("2145139b-64b4-475e-ba84-5efe83d53d8b"),
                            ShoppingListId = new Guid("49c7a8c0-0647-4380-a588-e8d88c039f06"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ArticleId = new Guid("c65e7d76-8af8-4e1c-b89e-3102248e73a6"),
                            ShoppingListId = new Guid("49c7a8c0-0647-4380-a588-e8d88c039f06"),
                            Amount = 300.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = "GRAM"
                        });
                });

            modelBuilder.Entity("Listomora.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DisableDate")
                        .HasColumnType("DateTime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_Role", "[Role] IN (0,1)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@cena.us",
                            FirstName = "John",
                            LastName = "Cena",
                            Password = "$argon2id$v=19$m=65536,t=3,p=1$ehpdI3z4ujA4SDfXx1Ou1w$d2Ez1LgQqGeh9D62OsfJUQOvs5k4T1N5qpOS5VeNBGQ",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("6ad52029-0225-48c4-a2b5-7aa35fec7056"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cr7@goat.com",
                            FirstName = "Cristiano",
                            LastName = "Ronaldo",
                            Password = "$argon2id$v=19$m=65536,t=3,p=1$GwBbis6x7S9Jib0/17cHIQ$oLa2jn0WxsHK4HpuMQBaVfjLM69KfH6Bq47sTvTOuRQ",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("0eb2993d-7fd5-4f29-9172-1b8f6aa80736"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lm10@goat.com",
                            FirstName = "Lionel",
                            LastName = "Messi",
                            Password = "$argon2id$v=19$m=65536,t=3,p=1$KRnjO15ytzYvIK++c9ieGw$ApU20crdRNgygzKPCol+6GtlPhCxIc/j65+pCp2sn+I",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Listomora.Domain.Models.Ingredient", b =>
                {
                    b.HasBaseType("Listomora.Domain.Models.Article");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cae52516-7547-4d4e-a289-358fd8891a98"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Pommes de terre",
                            Category = "CEREALS"
                        },
                        new
                        {
                            Id = new Guid("e5bebf1e-bd35-448c-a1a2-941e55687ff5"),
                            CreatorId = new Guid("6ad52029-0225-48c4-a2b5-7aa35fec7056"),
                            IsPublic = false,
                            Name = "Viande de veau",
                            Category = "MEAT"
                        },
                        new
                        {
                            Id = new Guid("1ed84abe-4c15-458f-82b8-a5a9bc34b5b5"),
                            CreatorId = new Guid("0eb2993d-7fd5-4f29-9172-1b8f6aa80736"),
                            IsPublic = true,
                            Name = "Filet de saumon",
                            Category = "FISH_AND_SEAFOODS"
                        },
                        new
                        {
                            Id = new Guid("82a56879-1d59-40f6-8a20-75cdcd2fe686"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Emmental rapé",
                            Category = "DAIRY_PRODUCTS"
                        },
                        new
                        {
                            Id = new Guid("97505262-64f9-4444-83cf-67c93d8161d5"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = false,
                            Name = "Blanc de poulet",
                            Category = "MEAT"
                        },
                        new
                        {
                            Id = new Guid("97796814-4f88-40a6-8d3d-98f46135be41"),
                            CreatorId = new Guid("6ad52029-0225-48c4-a2b5-7aa35fec7056"),
                            IsPublic = true,
                            Name = "Sel",
                            Category = "CONDIMENTS"
                        },
                        new
                        {
                            Id = new Guid("16c4a654-0f04-40eb-a23e-9d580c7062a8"),
                            CreatorId = new Guid("0eb2993d-7fd5-4f29-9172-1b8f6aa80736"),
                            IsPublic = false,
                            Name = "Poivre",
                            Category = "CONDIMENTS"
                        },
                        new
                        {
                            Id = new Guid("3d11a56b-1b6a-4581-940a-36eb4c25d01c"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Spaghetti",
                            Category = "CEREALS"
                        },
                        new
                        {
                            Id = new Guid("ac07af80-640a-4270-9d48-62f8c9b84df6"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Haricots verts",
                            Category = "LEGUMES"
                        },
                        new
                        {
                            Id = new Guid("2145139b-64b4-475e-ba84-5efe83d53d8b"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Cannelle",
                            Category = "CONDIMENTS"
                        },
                        new
                        {
                            Id = new Guid("4c500d54-1468-4a8c-81f5-ff846fb36b3d"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Moutarde",
                            Category = "CONDIMENTS"
                        },
                        new
                        {
                            Id = new Guid("4a5bda61-ac90-4faf-9ae1-139f81a17eb6"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Fraise",
                            Category = "FRUITS"
                        },
                        new
                        {
                            Id = new Guid("b09ea0c6-b53a-4a70-bff7-56dcfc5bb2d0"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Pomme",
                            Category = "FRUITS"
                        },
                        new
                        {
                            Id = new Guid("e6f1fd6a-abb7-4d84-bca8-aeff139dc88c"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Tomate",
                            Category = "VEGETABLES"
                        },
                        new
                        {
                            Id = new Guid("eaa7d8cb-f6ac-40b6-9cfe-6250acb41907"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Brocoli",
                            Category = "VEGETABLES"
                        },
                        new
                        {
                            Id = new Guid("46703052-e35c-4582-85a8-418f284e0ec8"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Mozzarella",
                            Category = "DAIRY_PRODUCTS"
                        },
                        new
                        {
                            Id = new Guid("9e736920-7440-4376-b485-1f192e0d7470"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Poulet",
                            Category = "MEAT"
                        },
                        new
                        {
                            Id = new Guid("c762d216-d6ab-43b6-bfe7-cab995c5aea9"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Saucisses",
                            Category = "MEAT"
                        },
                        new
                        {
                            Id = new Guid("794f67c2-7afb-495e-8570-6daad6cb4a0a"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Carotte",
                            Category = "VEGETABLES"
                        },
                        new
                        {
                            Id = new Guid("fcf05aed-90e9-47a0-b9b9-09af9bf0f2b9"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Huile d'olive",
                            Category = "FATS"
                        },
                        new
                        {
                            Id = new Guid("48f07af2-eefb-4097-a479-cc50a3117851"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Beurre",
                            Category = "FATS"
                        },
                        new
                        {
                            Id = new Guid("121a810d-3904-4cf1-9af4-063a2e56b62b"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Thon",
                            Category = "FISH_AND_SEAFOODS"
                        },
                        new
                        {
                            Id = new Guid("edf88fdd-0117-4aa4-b3a5-17be26c913f9"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Lait",
                            Category = "BEVERAGES"
                        },
                        new
                        {
                            Id = new Guid("1dd4a5f7-f93f-42ed-919d-c677f0dc0e7f"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Chocolat",
                            Category = "SWEET_PRODUCTS"
                        },
                        new
                        {
                            Id = new Guid("21d579a9-b2ae-4434-b7d5-45201001bca1"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Sucre",
                            Category = "SWEET_PRODUCTS"
                        },
                        new
                        {
                            Id = new Guid("c65e7d76-8af8-4e1c-b89e-3102248e73a6"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Crevettes",
                            Category = "FISH_AND_SEAFOODS"
                        },
                        new
                        {
                            Id = new Guid("aac50be3-c2ea-4642-a3d9-81f58299e012"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Pêche",
                            Category = "FRUITS"
                        },
                        new
                        {
                            Id = new Guid("d35633e3-34cb-48d2-aedc-5a65271357d2"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Pain",
                            Category = "BAKED_AND_PASTRIES"
                        },
                        new
                        {
                            Id = new Guid("3d956419-cd5b-41c5-9b2a-d7e5a990c838"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Œufs",
                            Category = "EGGS"
                        },
                        new
                        {
                            Id = new Guid("924c8c5b-9684-4b77-b5d0-80b0f1cf8b30"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Persil",
                            Category = "HERBS_AND_SPICES"
                        },
                        new
                        {
                            Id = new Guid("ff0cdcf7-aee0-4b9e-b520-8d0fb3b93047"),
                            CreatorId = new Guid("5bd4bf86-da80-438c-be55-a466ea3b994d"),
                            IsPublic = true,
                            Name = "Macaroni",
                            Category = "CEREALS"
                        });
                });

            modelBuilder.Entity("Listomora.Domain.Models.Article", b =>
                {
                    b.HasOne("Listomora.Domain.Models.User", "Creator")
                        .WithMany("CreatedArticles")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_Article_Creator");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Listomora.Domain.Models.ShoppingList", b =>
                {
                    b.HasOne("Listomora.Domain.Models.User", "Creator")
                        .WithMany("CreatedShoppingLists")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShoppingList_Creator");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Listomora.Domain.Models.ShoppingListLine", b =>
                {
                    b.HasOne("Listomora.Domain.Models.Article", "Article")
                        .WithMany("ShoppingListLines")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShoppingListLine_Article");

                    b.HasOne("Listomora.Domain.Models.ShoppingList", "ShoppingList")
                        .WithMany("ShoppingListLines")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShoppingListLine_ShoppingList");

                    b.Navigation("Article");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("Listomora.Domain.Models.Article", b =>
                {
                    b.Navigation("ShoppingListLines");
                });

            modelBuilder.Entity("Listomora.Domain.Models.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListLines");
                });

            modelBuilder.Entity("Listomora.Domain.Models.User", b =>
                {
                    b.Navigation("CreatedArticles");

                    b.Navigation("CreatedShoppingLists");
                });
#pragma warning restore 612, 618
        }
    }
}
